#!/bin/bash

FILE="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WCRONLOCATION="$(realpath "$(dirname $(readlink -f $DIR/$FILE))/../../../../")"

php $WCRONLOCATION/bin/console wcron:run